import { db } from "@/db";
import { betterAuth } from "better-auth";
import { admin } from "better-auth/plugins";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { Role } from "@/types/auth";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is not set");
}

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
  }),
  advanced: {
    database: {
      generateId: false, // We use UUIDs which are generated by the database
    },
  },
  emailAndPassword: {
    enabled: true,
    disableSignUp: true,
    minPasswordLength: 12,
  },
  user: {
    additionalFields: {
      phone: {
        type: "string",
        required: false,
      },
      accountNumber: {
        type: "string",
        required: false,
      },
      ssn: {
        type: "string",
        required: false,
      },
      diplomaId: {
        type: "string",
        required: false,
        references: {
          model: "diplomas",
          field: "id",
          onDelete: "restrict",
        },
      },
    },
  },
  plugins: [
    admin({
      defaultRole: Role.TEACHER,
    }),
  ],
});
