services:
  azl_db:
    image: postgres:17.6-alpine
    container_name: azl_db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - azl_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: azlapp-dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d azlapp-dev"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  azl_db_data:
